language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install flake8
script:
  - python setup.py build
  - flake8
  - python setup.py test
